const Images = {
  Pictures: {
    loginBG: require('../../assets/images/joker.jpg'),
    homeBg: require('../../assets/images/homeBg.png'),
    appBg: require('../../assets/images/Bg.png'),
    profile: require('../../assets/images/profile.png'),
    help: require('../../assets/images/help.png'),
    forgetBlur: require('../../assets/images/forgetBlur.png'),
    statusImg1: require('../../assets/images/statusImg1.png'),
    statusImg2: require('../../assets/images/statusImg2.png'),
    statusImg3: require('../../assets/images/statusImg3.png'),
    statusImg4: require('../../assets/images/statusImg4.png'),
    statusImg5: require('../../assets/images/statusImg5.png'),
    item1: require('../../assets/images/item1.png'),
    item2: require('../../assets/images/item2.png'),
    item3: require('../../assets/images/item3.png'),
    item4: require('../../assets/images/item4.png'),
    item5: require('../../assets/images/item5.png'),
    postImg1: require('../../assets/images/post1.png'),
  },
  Logos: {
    plusIcon: require('../../assets/images/plusIcon.png'),
    connect: require('../../assets/images/connect.png'),
    done: require('../../assets/images/done.png'),
    appLogo: require('../../assets/images/appLogo.png'),
    forgetPassword: require('../../assets/images/forgetPassword.png'),
    homeIcon: require('../../assets/images/homeIcon.png'),
    addIcon: require('../../assets/images/addIcon.png'),
    userIcon: require('../../assets/images/userIcon.png'),
    msgIcon: require('../../assets/images/msgIcon.png'),
    notificationIcon: require('../../assets/images/notificationIcon.png'),
    globe: require('../../assets/images/globe.png'),
  },
};

export {Images};
