const Images = {
  Pictures: {
    loginBG: require('../../assets/images/joker.jpg'),
    homeBg: require('../../assets/images/homeBg.png'),
    homeMainBg: require('../../assets/images/homeMainBg.jpg'),
    appBg: require('../../assets/images/Bg.png'),
    profile: require('../../assets/images/profile.png'),
    profile1: require('../../assets/images/profile1.png'),
    help: require('../../assets/images/help.png'),
    // forgetBlur: require('../../assets/images/forgetBlur.png'),
    statusImg1: require('../../assets/images/statusImg1.png'),
    statusImg2: require('../../assets/images/statusImg2.png'),
    statusImg3: require('../../assets/images/statusImg3.png'),
    statusImg4: require('../../assets/images/statusImg4.png'),
    statusImg5: require('../../assets/images/statusImg5.png'),
    productcackImg1: require('../../assets/images/productcack.png'),
    productcackImg2: require('../../assets/images/productcack2.png'),
    productcackImg3: require('../../assets/images/productcack3.png'),
    productcackImg4: require('../../assets/images/item4.png'),
    productcackImg5: require('../../assets/images/item5.png'),
    item1: require('../../assets/images/item1.png'),
    item2: require('../../assets/images/item2.png'),
    item3: require('../../assets/images/item3.png'),
    item4: require('../../assets/images/item4.png'),
    item5: require('../../assets/images/item5.png'),
    postImg1: require('../../assets/images/post1.png'),
    talent: require('../../assets/images/Talent.png'),
  },
  Logos: {
    plusIcon: require('../../assets/images/plusIcon.png'),
    connect: require('../../assets/images/connect.png'),
    done: require('../../assets/images/done.png'),
    appLogo: require('../../assets/images/appLogo.png'),
    forgetPassword: require('../../assets/images/forgetPassword.png'),
    homeIcon: require('../../assets/images/homeIcon.png'),
    addIcon: require('../../assets/images/addIcon.png'),
    userIcon: require('../../assets/images/userIcon.png'),
    msgIcon: require('../../assets/images/msgIcon.png'),
    notificationIcon: require('../../assets/images/notificationIcon.png'),
    globe: require('../../assets/images/globe.png'),
    shareIcon: require('../../assets/images/shareIcon.png'),
    favoriteIcon: require('../../assets/images/favoriteIcon.png'),
    msgColorIcon: require('../../assets/images/msgColorIcon.png'),
  },
  Icons: {
    // Star: require('../../assets/images/starIcon.png'),
    Document: require('../../assets/images/document.png'),
    Logout: require('../../assets/images/logout.png'),
    Account: require('../../assets/images/account.png'),
    arrowforward: require('../../assets/images/arrow-forward.png'),
    Save: require('../../assets/images/save.png'),
    document2: require('../../assets/images/document2.png'),
    privacy: require('../../assets/images/privacy.png'),
    check: require('../../assets/images/check.png'),
    card1: require('../../assets/images/card1.png'),
    card2: require('../../assets/images/card2.png'),
    card3: require('../../assets/images/card3.png'),
    card4: require('../../assets/images/card4.png'),
    card5: require('../../assets/images/card5.png'),
    premium: require('../../assets/images/premium.png'),
    post: require('../../assets/images/post.png'),
    PhotoVideo: require('../../assets/images/photo-video.png'),
    yes: require('../../assets/images/yes.png'),
    question: require('../../assets/images/question.png'),
    Key: require('../../assets/images/key.png'),
    lock1: require('../../assets/images/lock1.png'),
    add1: require('../../assets/images/add1.png'),
    setting1: require('../../assets/images/setting1.png'),
    user1: require('../../assets/images/user1.png'),
<<<<<<< Updated upstream
  },
=======
    play: require('../../assets/images/play.png'),

  }
>>>>>>> Stashed changes
};

export {Images};
